# Generated by Django 6.0.7 on 2026-07-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
