# Generated by Django 6.0.7 on 2026-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_paste_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
