# Generated by Django 6.0.7 on 2026-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_paste_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
